### PR TITLE
Fix 1.42.0

### PR DESCRIPTION
**Pull request by janjagusch**
Trying to fix https://github.com/conda-forge/grpcio-tools-feedstock/pull/8.

- Rerendered the feedstock
- Reset build number to 0
- Added myself as maintainer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by janjagusch** [comment]
@martinRenou, could you take a quick look at this? I want to help keep this feedstock up to date. 😇

**Comment by janjagusch** [comment]
ping, @martinRenou. :)

**Comment by janjagusch** [comment]
> ping, @martinRenou. :)

one more ping, @martinRenou. sorry for spamming you. 😇

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
