### PR TITLE
grpcio-tools v1.55.0 with MAC_SDK 11

### PR DESCRIPTION
**Pull request by DerThorsten**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by DerThorsten** [comment]
@conda-forge-admin, please rerender

**Comment by DerThorsten** [comment]
@conda-forge-admin, please rerender

**Comment by DerThorsten** [comment]
@conda-forge-admin, please rerender

**Comment by DerThorsten** [comment]
this is using `MACOSX_SDK_VERSION` / `MACOSX_DEPLOYMENT_TARGET` 11

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by DerThorsten** [comment]
I give it one more try with only requiring  the `MACOSX_SDK_VERSION` but not `MACOSX_DEPLOYMENT_TARGET` since it is only a mission macro

**Comment by DerThorsten** [comment]
pinning @conda-forge/core as suggested by https://conda-forge.org/docs/maintainer/knowledge_base.html since we change the `MACOSX_SDK_VERSION`

**Comment by martinRenou** [comment]
1.55 was yanked from PyPi https://pypi.org/project/grpcio

**Pull request closed without merging**
